spring:
  application:
    name: "JobSearch"
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

#====================== DataBase ========================

  datasource:
    url: jdbc:h2:./db/JobSearch_2DB;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  jpa:
    hibernate:
      ddl-auto: validate

#====================== DataBase ========================

logging:
  level:
    root: info
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs
