spring:
  application:
    name: "JobSearch"

#====================== DataBase ========================

  datasource:
    url: jdbc:h2:./db/JobSearchDB;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

#====================== DataBase ========================
