spring:
  application:
    name: "JobSearch"
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

#====================== DataBase ========================

  datasource:
    url: jdbc:h2:./db/JobSearch_2DB;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  jpa:
    hibernate:
      ddl-auto: validate

#====================== DataBase ========================

  #============================= Mail config

  mail:
    host: smtp.gmail.com
    username: izlax6002@gmail.com
    password: "sznj qgnx hsjj fyuz"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#============================= Mail config


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs


